language: csharp
solution: LtiAdvantage.sln
mono: none
dotnet: 2.2
dist: xenial
script:
 - dotnet restore
 - dotnet build
 - dotnet test test/LtiAdvantage.IntegrationTests/LtiAdvantage.IntegrationTests.csproj
 - dotnet test test/LtiAdvantage.UnitTests/LtiAdvantage.UnitTests.csproj
